version: '3'

services:
  database:
    image: postgres
    volumes:
        - ./dbdata:/var/lib/postgresql/data
    env_file:
        - ./development.env

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=redis
    env_file:
      - ./development.env

  web:
    build: ./
    depends_on:
      - "database"
      - "redis"
    command: bash -c "python3 manage.py makemigrations &&
                      python3 manage.py migrate &&
                      python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./development.env
