version: '3'

services:
  database:
    image: postgres
    env_file:
        - ./development.env
    volumes:
        - ./dbdata:/var/lib/postgresql/data

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=redis

  web:
    build: ./
    depends_on:
      - "database"
      - "redis"
    command: bash -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True  # set to False in production
      - DB_NAME=officemanager
      - DB_USER=officemanager
      - DB_PASSWORD=qweqwe123
      - DB_HOST=database
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
