version: '2'

services:
  database:
    image: postgres
    env_file:
        - .env
    volumes:
        - ./dbdata:/var/lib/postgresql/data
    env_file:
        - .env

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=redis
    env_file:
      - .env

  web:
    build: ./
    depends_on:
      - "database"
      - "redis"
    command: bash -c "python3 manage.py collectstatic --noinput &&
                      python3 manage.py makemigrations &&
                      python3 manage.py migrate &&
                      python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./static:/opt/public/statics
      - ./src:/opt/office-manager

  nginx:
    image: nginx
    depends_on:
      - "web"
    volumes:
     - ./nginx_site.conf:/etc/nginx/conf.d/nginx_site.conf
     - ./static:/opt/nginx_static
    ports:
     - "80:80"
    command: /bin/bash -c "cp /etc/nginx/conf.d/nginx_site.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
